// Code generated by "types-parser -source-package github.com/ubuntu/authd/internal/proto/authd -types authd.GAMResponse_AuthenticationMode -types-aliases Mode -package auth -output ./authmode.go -converter ../../internal/proto/authd/authmode.go -converter-import github.com/ubuntu/authd/brokers/auth -converter-package authd"; DO NOT EDIT.

package auth

// Mode is a wrapper for [authd.GAMResponse_AuthenticationMode].
type Mode struct {
	Id string `json:"id,omitempty"`
	Label string `json:"label,omitempty"`
}

func (m Mode) GetId() string {
	return m.Id
}

func (m Mode) GetLabel() string {
	return m.Label
}


