name: Report an issue
description: Create a bug report to fix an issue
title: "Issue: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: >
        :warning: **Please do not report security vulnerabilities here**

        Be careful with sensitive information and security vulnerabilities. In order to report bugs that could contain
        sensitive information, use [Launchpad](https://bugs.launchpad.net/ubuntu/+source/authd/+filebug) instead.


        Thanks for taking the time to report an issue and help improve authd! Please fill out the form below as
        best as you can so that we can help you.


        Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general
        support or usage questions, use [Ubuntu Discourse](https://discourse.ubuntu.com/c/desktop/8).


        By submitting an Issue to this repository, you agree to the terms within the
        [Ubuntu Code of Conduct](https://ubuntu.com/community/code-of-conduct).


        **Troubleshooting**

        Please read our [Troubleshooting wiki page](https://github.com/ubuntu/authd/wiki/06--Troubleshooting)
        and see if you can find a solution to your problem there.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      options:
        - label: I have searched the existing issues and found none that matched mine
          required: true
  - type: textarea
    attributes:
      label: Describe the issue
      description: >
        Provide a clear and concise description of what the issue is, including what you expected to happen.

        Please specify if the option is in the graphical display manager or in the terminal. If it is with the graphical
        display manager, try to login with another local user, and open a terminal. Then, try to login with "login"
        and see if you can reproduce the issue there too. State so in the description.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: >
        Specify the steps you took when you encountered the issue and which behavior you expected.
        Are you able to reproduce the issue consistently?
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...

        Please include screenshots (you can drag any image here) where applicable. Redact any sensitive information.
    validations:
      required: false
  - type: textarea
    attributes:
      label: "System information and logs"
      description: |
        Copy this command and run it in a terminal. It will open a text editor with the system information and logs. Paste the output below. Redact any sensitive information from the logs.
        ```bash
        TMPFILE=$(mktemp authd-system-info-XXXXXX.md)
        if command -v xdg-open > /dev/null && [ -n "${DISPLAY:-}" ]; then authd_editor=xdg-open; elif [ -n "${EDITOR:-}" ]; then authd_editor=$EDITOR; fi
        cat > "$TMPFILE" <<EOF && ${authd_editor:-editor} "$TMPFILE"
        #### authd version
        \`\`\`
        $(/usr/libexec/authd version)
        \`\`\`

        #### authd-msentraid broker version
        \`\`\`
        $(snap info authd-msentraid 2>/dev/null)
        \`\`\`

        #### gnome-shell version
        \`\`\`
        $(apt policy gnome-shell 2>/dev/null)
        \`\`\`

        #### Distribution
        \`\`\`
        $(lsb_release -a)
        \`\`\`

        #### Logs
        \`\`\`
        $(journalctl -o short-monotonic --lines 500  _SYSTEMD_UNIT=authd.service \+ UNIT=authd.service \+ \
          _SYSTEMD_UNIT=snap.authd-msentraid.authd-msentraid.service \+ UNIT=snap.authd-msentraid.authd-msentraid.service \+ SYSLOG_IDENTIFIER=authd-msentraid \+ \
          _SYSTEMD_UNIT=snap.authd-google.authd-google.service \+ UNIT=snap.authd-google.authd-google.service \+ SYSLOG_IDENTIFIER=authd-google \+ \
          '_CMDLINE="gdm-session-worker [pam/gdm-authd]"' | sed -E 's/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}/<UUID redacted>/g')
        \`\`\`

        #### authd broker configuration
        $(sudo sh -c 'if ! find /etc/authd/brokers.d -name \*.conf | grep -q .; then echo ":warning: No config files in /etc/authd/brokers.d/"; else for f in /etc/authd/brokers.d/*.conf; do echo "#### $f"; echo "\`\`\`";  cat $f; echo "\`\`\`"; done; fi')

        #### authd-msentraid configuration
        \`\`\`
        $(sudo cat 2>&1 /var/snap/authd-msentraid/current/broker.conf | sed -E 's/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}/<UUID redacted>/g')
        \`\`\`

        #### authd-google configuration
        \`\`\`
        $(sudo cat 2>&1 /var/snap/authd-google/current/broker.conf | sed -E 's/client_id = .*/client_id = <redacted>/g' | sed -E 's/client_secret = .*/client_secret = <redacted>/g')
        \`\`\`

        EOF
        ```

      placeholder: >
        Paste the output of the above command here. Redact any sensitive
        information from the logs.

  - type: checkboxes
    attributes:
      label: Double check your logs
      options:
        - label: I have redacted any sensitive information from the logs
          required: true
