name: Request a feature
description: Suggest new functionality or improvements for this project
title: "Feature: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: >
        :warning: **Please do not report security vulnerabilities here**

        Be careful with sensitive information and security vulnerabilities. In order to report bugs that could contain
        sensitive information, use [Launchpad](https://bugs.launchpad.net/ubuntu/+source/authd/+filebug) instead.
        On Ubuntu machines, you can use `ubuntu-bug authd` to collect relevant information.


        Thanks for taking the time to report an issue and help improve authd! Please fill out the form below as
        best as you can so that we can help you.

        Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general
        support or usage questions, use [Ubuntu Discourse](https://discourse.ubuntu.com/c/desktop/8).

        By submitting an Issue to this repository, you agree to the terms within the
        [Ubuntu Code of Conduct](https://ubuntu.com/community/code-of-conduct).
  - type: checkboxes
    attributes:
      label: Is there an existing request for this feature?
      options:
        - label: I have searched the existing issues and found none that matched mine
          required: true
  - type: textarea
    attributes:
      label: Describe the feature
      description: >
        A clear and concise description of what the problem is. Ex.: \"I'm always frustrated when ...\"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the ideal solution
      description: |
        A clear and concise description of what you want to happen.
  - type: textarea
    attributes:
      label: Alternatives and current workarounds
      description: |
        A clear and concise description of any alternatives you've considered or any workarounds that are currently in
        place.
  - type: textarea
    attributes:
      label: "System information and logs"
      description: |
        Provide details about the environment you experienced the issue in. Change msentraid for the provider you are using:
      value: |
        ### Environment
        * broker version: please run `snap info authd-msentraid`
        * authd version: please run `/usr/libexec/authd version`
        * gnome shell version: please run `apt policy gnome-shell`
        * Distribution: (**NAME** in `/etc/os-release`)
        * Distribution version: (**VERSION_ID** on `/etc/os-release`):

        ### Log files
        Please redact/remove sensitive information:

        #### Authd entries:

        ```raw
        journalctl -u authd.service
        ```

        ####  MS Entra ID broker entries:

        ```raw
        journalctl -u snap.authd-msentraid.authd-msentraid.service
        ```

        ### Application settings

        Please redact/remove sensitive information:

        ####  Broker configuration:

        ```raw
        cat /var/snap/authd-msentraid/current/broker.conf
        ```

        ####  Broker authd configuration:

        ```raw
        cat /etc/authd/brokers.d/msentraid.conf
        ```

  - type: textarea
    attributes:
      label: Relevant information
      description: >
        Please look at our [Troubleshooting guide](https://github.com/ubuntu/authd/wiki/05--Troubleshooting) and provide logs for both authd and the oidc provider package.
      placeholder: Remember to redact any sensitive information from them.
  - type: checkboxes
    attributes:
      label: Double check your logs
      options:
        - label: I have redacted any sensitive information from the logs
          required: true
