// Code generated by "types-parser -source-package github.com/ubuntu/authd/internal/proto/authd -types authd.UILayout -types-aliases UILayout -package layouts -output ./uilayout.go -converter ../../internal/proto/authd/uilayout.go -converter-import github.com/ubuntu/authd/brokers/layouts -converter-package authd"; DO NOT EDIT.

package authd

import "github.com/ubuntu/authd/brokers/layouts"

func NewFromUILayout(u layouts.UILayout) *UILayout {
	return &UILayout{
		Type: u.Type,
		Label: u.Label,
		Button: u.Button,
		Wait: u.Wait,
		Entry: u.Entry,
		Content: u.Content,
		Code: u.Code,
		RendersQrcode: u.RendersQrcode,
	}
}

func (u *UILayout) ToUILayout() layouts.UILayout {
	return layouts.UILayout{
		Type: u.Type,
		Label: u.Label,
		Button: u.Button,
		Wait: u.Wait,
		Entry: u.Entry,
		Content: u.Content,
		Code: u.Code,
		RendersQrcode: u.RendersQrcode,
	}
}
