// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: pam.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// state represents the stage object for the UI.
type Stage int32

const (
	// Stage_userSelection is to select a user.
	Stage_userSelection Stage = 0
	// Stage_brokerSelection is to select a broker.
	Stage_brokerSelection Stage = 1
	// Stage_authModeSelection is to select an authentication mode.
	Stage_authModeSelection Stage = 2
	// Stage_challenge lets the user enter a secret or wait for authentication from the broker.
	Stage_challenge Stage = 3
)

// Enum value maps for Stage.
var (
	Stage_name = map[int32]string{
		0: "userSelection",
		1: "brokerSelection",
		2: "authModeSelection",
		3: "challenge",
	}
	Stage_value = map[string]int32{
		"userSelection":     0,
		"brokerSelection":   1,
		"authModeSelection": 2,
		"challenge":         3,
	}
)

func (x Stage) Enum() *Stage {
	p := new(Stage)
	*p = x
	return p
}

func (x Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_pam_proto_enumTypes[0].Descriptor()
}

func (Stage) Type() protoreflect.EnumType {
	return &file_pam_proto_enumTypes[0]
}

func (x Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stage.Descriptor instead.
func (Stage) EnumDescriptor() ([]byte, []int) {
	return file_pam_proto_rawDescGZIP(), []int{0}
}

var File_pam_proto protoreflect.FileDescriptor

var file_pam_proto_rawDesc = string([]byte{
	0x0a, 0x09, 0x70, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x70, 0x61, 0x6d,
	0x2a, 0x55, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x67, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x75, 0x73, 0x65,
	0x72, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f,
	0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x10,
	0x01, 0x12, 0x15, 0x0a, 0x11, 0x61, 0x75, 0x74, 0x68, 0x4d, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6c,
	0x6c, 0x65, 0x6e, 0x67, 0x65, 0x10, 0x03, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x62, 0x75, 0x6e, 0x74, 0x75, 0x2f, 0x61, 0x75, 0x74,
	0x68, 0x64, 0x2f, 0x70, 0x61, 0x6d, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_pam_proto_rawDescOnce sync.Once
	file_pam_proto_rawDescData []byte
)

func file_pam_proto_rawDescGZIP() []byte {
	file_pam_proto_rawDescOnce.Do(func() {
		file_pam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pam_proto_rawDesc), len(file_pam_proto_rawDesc)))
	})
	return file_pam_proto_rawDescData
}

var file_pam_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pam_proto_goTypes = []any{
	(Stage)(0), // 0: pam.Stage
}
var file_pam_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pam_proto_init() }
func file_pam_proto_init() {
	if File_pam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pam_proto_rawDesc), len(file_pam_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pam_proto_goTypes,
		DependencyIndexes: file_pam_proto_depIdxs,
		EnumInfos:         file_pam_proto_enumTypes,
	}.Build()
	File_pam_proto = out.File
	file_pam_proto_goTypes = nil
	file_pam_proto_depIdxs = nil
}
