package tempentries

import (
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/ubuntu/authd/internal/testutils/golden"
	"github.com/ubuntu/authd/internal/users/idgenerator"
	"github.com/ubuntu/authd/internal/users/types"
)

func TestRegisterGroup(t *testing.T) {
	t.Parallel()

	gidToGenerate := uint32(12345)

	tests := map[string]struct {
		groupName      string
		gidsToGenerate []uint32

		wantErr bool
	}{
		"Successfully register a new group": {},
		"Successfully register a group if the first generated GID is already in use": {
			gidsToGenerate: []uint32{0, gidToGenerate}, // GID 0 (root) always exists
		},

		"Error when name is already in use": {groupName: "root", wantErr: true},
	}
	for name, tc := range tests {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			if tc.groupName == "" {
				tc.groupName = "authd-temp-groups-test"
			}

			if tc.gidsToGenerate == nil {
				tc.gidsToGenerate = []uint32{gidToGenerate}
			}

			idGeneratorMock := &idgenerator.IDGeneratorMock{GIDsToGenerate: tc.gidsToGenerate}
			records := newTemporaryGroupRecords(idGeneratorMock)

			gid, cleanup, err := records.RegisterGroup(tc.groupName)
			if tc.wantErr {
				require.Error(t, err, "RegisterGroup should return an error, but did not")
				return
			}
			require.NoError(t, err, "RegisterGroup should not return an error, but did")
			require.Equal(t, gidToGenerate, gid, "GID should be the one generated by the IDGenerator")
			// Check that the temporary group was created
			group, err := records.GroupByID(gid)
			require.NoError(t, err, "GroupByID should not return an error, but did")
			checkGroup(t, group)

			// Delete the temporary group
			cleanup()

			// Check that the temporary group was deleted
			_, err = records.GroupByID(gid)
			require.Error(t, err, "GroupByID should return an error, but did not")
		})
	}
}

func TestGroupByIDAndName(t *testing.T) {
	t.Parallel()

	groupName := "authd-temp-groups-test"
	gidToGenerate := uint32(12345)

	tests := map[string]struct {
		registerGroup       bool
		groupAlreadyRemoved bool
		byName              bool

		wantErr bool
	}{
		"Successfully get a group by ID":   {registerGroup: true},
		"Successfully get a group by name": {registerGroup: true, byName: true},

		"Error when group is not registered - GroupByID":   {wantErr: true},
		"Error when group is not registered - GroupByName": {byName: true, wantErr: true},
		"Error when group is already removed - GroupByID": {
			registerGroup:       true,
			groupAlreadyRemoved: true,
			wantErr:             true,
		},
		"Error when group is already removed - GroupByName": {
			registerGroup:       true,
			groupAlreadyRemoved: true,
			byName:              true,
			wantErr:             true,
		},
	}

	for name, tc := range tests {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			idGeneratorMock := &idgenerator.IDGeneratorMock{GIDsToGenerate: []uint32{gidToGenerate}}
			records := newTemporaryGroupRecords(idGeneratorMock)

			if tc.registerGroup {
				gid, cleanup, err := records.RegisterGroup(groupName)
				require.NoError(t, err, "RegisterGroup should not return an error, but did")
				require.Equal(t, gidToGenerate, gid, "GID should be the one generated by the IDGenerator")

				if tc.groupAlreadyRemoved {
					cleanup()
				} else {
					defer cleanup()
				}
			}

			var group types.GroupEntry
			var err error
			if tc.byName {
				group, err = records.GroupByID(gidToGenerate)
			} else {
				group, err = records.GroupByName(groupName)
			}

			if tc.wantErr {
				require.Error(t, err, "GroupByID should return an error, but did not")
				return
			}
			require.NoError(t, err, "GroupByID should not return an error, but did")
			checkGroup(t, group)
		})
	}
}

func checkGroup(t *testing.T, group types.GroupEntry) {
	t.Helper()

	// The passwd field is randomly generated, so unset it before comparing the group with the golden file.
	require.NotEmpty(t, group.Passwd, "Passwd should not be empty")
	group.Passwd = ""

	golden.CheckOrUpdateYAML(t, group)
}
