Hide
Type "./pam_authd login socket=${AUTHD_TESTS_CLI_AUTHENTICATE_TESTS_SOCK} force_native_client=true"
Enter
Sleep 300ms
Show

Hide
Type "user-can-reset2"
Enter
Sleep 300ms
Show

Hide
Type "2"
Enter
Sleep 500ms
Show

Hide
Type "goodpass"
Enter
Sleep 2s
Show

Hide
Type "1"
Enter
Sleep 300ms
Show

Hide
Type "authd2404"
Enter
Sleep 2s
Show

Hide
Type "authd2404"
Enter
Sleep 2s
Show

Hide
Enter
Sleep 2s
Show

Sleep 300ms
