Hide
Wait
Type "${AUTHD_TEST_TAPE_COMMAND}"
Enter
Wait /Username:$/
Show

Hide
Type "user-integration-same-new-password"
Show

Hide
Enter
Wait+Screen /Choose your provider:\n>/
Wait
Show

Hide
Type "2"
Enter
Wait+Screen /Gimme your password:\n>/
Wait
Show

Hide
Type "goodpass"
Enter
Wait+Screen /Enter your new password:\n>/
Wait
Show

Hide
Type "goodpass"
Show

Hide
Enter
Wait+Screen /Enter your new password:\n>/
Wait
Show

Hide
Type "authd2404"
Enter
Wait+Screen /Confirm Password:\n>/
Wait
Show

Hide
Type "authd2404"
Show

Hide
Enter
Wait
Show
