Hide
Wait
Type "${AUTHD_TEST_TAPE_COMMAND}"
Enter
Wait+Prompt /Choose your provider/
Show

Hide
Type "2"
Enter
Wait+Prompt /Gimme your password/
Show

Hide
Type "r"
Enter
Wait+Prompt /Choose your authentication method/
Wait+Screen /8\. Authentication code/
Show

Hide
Type "8"
Enter
Wait+Prompt /Choose action/
Show

Hide
Type "1"
Enter
Wait+Prompt /Enter your one time credential/
Show

Hide
Type "temporary pass0"
Enter
Wait
Show

Hide
Wait
Type "${AUTHD_TEST_TAPE_COMMAND}"
Enter
Wait+Prompt /Choose action/
Show

Hide
Type "1"
Enter
Wait+Prompt /Enter your one time credential/
Show

Hide
Type "temporary pass0"
Enter
Wait
Show
