Hide
Wait
Type "${AUTHD_TEST_TAPE_COMMAND}"
Enter
Wait+Prompt /Choose your provider/
Show

Hide
Type "r"
Enter
Wait+Prompt /Choose your provider/
Show

Hide
Type "2"
Enter
Wait+Prompt /Gimme your password/
Show

Hide
Type "r"
Enter
Wait+Prompt /Choose your authentication method/
Show

Hide
Type "r"
Enter
Wait+Prompt /Choose your provider/
Show

Hide
Type "r"
Enter
Wait+Prompt /Choose your provider/
Show

Hide
Type "r"
Enter
Wait+Prompt /Choose your provider/
Show

Hide
Type "2"
Enter
Wait+Prompt /Gimme your password/
Show

Hide
Type "goodpass"
Enter
Wait
Show
