//go:build generate && proto

//go:generate ../../../../tools/generate-proto.sh --with-grpc grpctestservice.proto

// Package grpctestservice contains the autogenerated GRPC API.
package grpctestservice
