Hide
Type "./pam_authd login socket=${AUTHD_TESTS_CLI_AUTHENTICATE_TESTS_SOCK}"
Enter
Sleep ${AUTHD_SLEEP_DEFAULT}
Show

Hide
Escape
Backspace
Type "user-integration-max-attempts"
Sleep ${AUTHD_SLEEP_DEFAULT}
Show

Hide
Enter
Sleep ${AUTHD_SLEEP_DEFAULT}
Show

Hide
Type "2"
Sleep ${AUTHD_SLEEP_DEFAULT}
Show

Hide
Type "wrongpass"
Enter
Sleep ${AUTHD_SLEEP_DEFAULT}
Show

Hide
Type "wrongpass"
Enter
Sleep ${AUTHD_SLEEP_DEFAULT}
Show

Hide
Type "wrongpass"
Enter
Sleep ${AUTHD_SLEEP_DEFAULT}
Show

Hide
Type "wrongpass"
Enter
Sleep ${AUTHD_SLEEP_DEFAULT}
Show

Hide
Type "wrongpass"
Enter
Sleep ${AUTHD_SLEEP_DEFAULT}
Show

Sleep ${AUTHD_SLEEP_DEFAULT}
