Hide
Type "./pam_authd login socket=${AUTHD_TESTS_CLI_AUTHENTICATE_TESTS_SOCK}"
Enter
Sleep 300ms
Show

Hide
Escape
Backspace
Type "user-mfa"
Sleep 300ms
Show

Hide
Enter
Sleep 300ms
Show

Hide
Type "2"
Sleep 300ms
Show

Hide
Escape
Sleep 300ms
Show

Hide
Type "1"
Sleep 300ms
Show

Hide
Type "goodpass"
Enter
Sleep 2s
Show

Hide
Escape
Sleep 500ms
Show

Hide
Enter
Sleep 500ms
Show

Hide
Sleep 5s
Show

Hide
Escape
Sleep 500ms
Show

Hide
Enter
Sleep 1s
Show

Hide
Sleep 5s
Show

Sleep 300ms
