Hide
Type "./pam_authd passwd socket=${AUTHD_TESTS_CLI_AUTHTOK_TESTS_SOCK}"
Enter
Sleep 300ms
Show

Hide
Escape
Backspace
Type "user-integration-bad-password"
Sleep 300ms
Show

Hide
Enter
Sleep 300ms
Show

Hide
Type "2"
Sleep 300ms
Show

Hide
Type "goodpass"
Enter
Sleep 2s
Show

Hide
Sleep 300ms
Enter
Show

Hide
Type "1234"
Sleep 300ms
Enter
Show

Hide
Type "12345678"
Sleep 300ms
Enter
Show

Hide
Type "authd2404"
Sleep 300ms
Enter
Show

Hide
Type "123456789"
Sleep 300ms
Show

Hide
Enter
Sleep 2s
Show

Hide
Type "authd2404"
Sleep 300ms
Enter
Show

Hide
Type "authd2404"
Sleep 300ms
Show

Hide
Enter
Sleep 2s
Show

Sleep 300ms
