Hide
Type "if [ -v AUTHD_PAM_CLI_TERM ]; then export TERM=${AUTHD_PAM_CLI_TERM}; fi"
Enter
Sleep 300ms
Show

Hide
Type "./pam_authd login socket=${AUTHD_TESTS_CLI_AUTHENTICATE_TESTS_SOCK}"
Enter
Sleep 800ms
Show

Hide
Type "2"
Sleep 300ms
Show

Hide
Escape
Sleep 300ms
Show

Hide
Type "6"
Sleep 300ms
Show

Hide
Tab
Sleep 300ms
Show

Hide
Enter
Sleep 800ms
Show

Hide
Enter
Sleep 800ms
Show

Hide
Enter
Sleep 800ms
Show

Hide
Enter
Sleep 1s
Show

Hide
Sleep 5s
Show

Sleep 300ms
