Hide
Type "./pam_authd login socket=${AUTHD_TESTS_CLI_AUTHENTICATE_TESTS_SOCK}"
Enter
Sleep 300ms
Show

Hide
Escape
Backspace
Type "user-integration-remember-mode"
Sleep 300ms
Show

Hide
Enter
Sleep 300ms
Show

Hide
Type "2"
Sleep 300ms
Escape
Sleep 300ms
Show

Hide
Type "7"
Sleep 300ms
Show

Hide
Type "temporary pass0"
Enter
Sleep 2s
Show

Hide
Type "./pam_authd login socket=${AUTHD_TESTS_CLI_AUTHENTICATE_TESTS_SOCK}"
Enter
Sleep 300ms
Show

Hide
Escape
Backspace
Type "user-integration-remember-mode"
Sleep 300ms
Show

Hide
Enter
Sleep 300ms
Show

Hide
Type "temporary pass0"
Enter
Sleep 2s
Show

Sleep 300ms
