// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.23.4
// source: gdm.proto

package gdm

import (
	authd "github.com/ubuntu/authd/internal/proto/authd"
	proto "github.com/ubuntu/authd/pam/internal/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataType int32

const (
	// DataType_unknownType is an unknown DataType.
	DataType_unknownType DataType = 0
	// DataType_hello is an hello DataType.
	DataType_hello DataType = 1
	// DataType_event is an event DataType.
	DataType_event DataType = 2
	// DataType_eventAck is an event DataType.
	DataType_eventAck DataType = 3
	// DataType_request is a request DataType.
	DataType_request DataType = 4
	// DataType_response is a response DataType.
	DataType_response DataType = 5
	// DataType_poll is a poll DataType.
	DataType_poll DataType = 6
	// DataType_pollResponse is a poll response DataType.
	DataType_pollResponse DataType = 7
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "unknownType",
		1: "hello",
		2: "event",
		3: "eventAck",
		4: "request",
		5: "response",
		6: "poll",
		7: "pollResponse",
	}
	DataType_value = map[string]int32{
		"unknownType":  0,
		"hello":        1,
		"event":        2,
		"eventAck":     3,
		"request":      4,
		"response":     5,
		"poll":         6,
		"pollResponse": 7,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_gdm_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_gdm_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{0}
}

type RequestType int32

const (
	// RequestType_unknownRequest is an unknown request RequestType.
	RequestType_unknownRequest RequestType = 0
	// RequestType_updateBrokersList is an update brokers list RequestType.
	RequestType_updateBrokersList RequestType = 1
	// RequestType_composeAuthenticationView is an compose authentication view RequestType.
	RequestType_composeAuthenticationView RequestType = 2
	// RequestType_uiLayoutCapabilities is an ui layout capabilities RequestType.
	RequestType_uiLayoutCapabilities RequestType = 3
	// RequestType_changeStage is a change stage RequestType.
	RequestType_changeStage RequestType = 4
)

// Enum value maps for RequestType.
var (
	RequestType_name = map[int32]string{
		0: "unknownRequest",
		1: "updateBrokersList",
		2: "composeAuthenticationView",
		3: "uiLayoutCapabilities",
		4: "changeStage",
	}
	RequestType_value = map[string]int32{
		"unknownRequest":            0,
		"updateBrokersList":         1,
		"composeAuthenticationView": 2,
		"uiLayoutCapabilities":      3,
		"changeStage":               4,
	}
)

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}

func (x RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_gdm_proto_enumTypes[1].Descriptor()
}

func (RequestType) Type() protoreflect.EnumType {
	return &file_gdm_proto_enumTypes[1]
}

func (x RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestType.Descriptor instead.
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{1}
}

type EventType int32

const (
	// EventType_unknownEvent is an unknown EventType.
	EventType_unknownEvent EventType = 0
	// EventType_userSelected is a user selected EventType.
	EventType_userSelected EventType = 1
	// EventType_brokersReceived is a broker received EventType.
	EventType_brokersReceived EventType = 2
	// EventType_brokerSelected is a broker selected EventType.
	EventType_brokerSelected EventType = 3
	// EventType_authModesReceived is an auth modes received EventType.
	EventType_authModesReceived EventType = 4
	// EventType_authModeSelected is an auth mode selected EventType.
	EventType_authModeSelected EventType = 5
	// EventType_reselectAuthMode is an reselect auth mode selected EventType.
	EventType_reselectAuthMode EventType = 6
	// EventType_authEvent is an auth event EventType.
	EventType_authEvent EventType = 7
	// EventType_uiLayoutReceived is an UI Layout Received EventType.
	EventType_uiLayoutReceived EventType = 8
	// EventType_startAuthentication is a start authentication EventType.
	EventType_startAuthentication EventType = 9
	// EventType_isAuthenticatedRequested is an authentication request EventType.
	EventType_isAuthenticatedRequested EventType = 10
	// EventType_isAuthenticationCancelled is authentication cancellation EventType.
	EventType_isAuthenticatedCancelled EventType = 11
	// EventType_stageChanged is stage changed EventType.
	EventType_stageChanged EventType = 12
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "unknownEvent",
		1:  "userSelected",
		2:  "brokersReceived",
		3:  "brokerSelected",
		4:  "authModesReceived",
		5:  "authModeSelected",
		6:  "reselectAuthMode",
		7:  "authEvent",
		8:  "uiLayoutReceived",
		9:  "startAuthentication",
		10: "isAuthenticatedRequested",
		11: "isAuthenticatedCancelled",
		12: "stageChanged",
	}
	EventType_value = map[string]int32{
		"unknownEvent":             0,
		"userSelected":             1,
		"brokersReceived":          2,
		"brokerSelected":           3,
		"authModesReceived":        4,
		"authModeSelected":         5,
		"reselectAuthMode":         6,
		"authEvent":                7,
		"uiLayoutReceived":         8,
		"startAuthentication":      9,
		"isAuthenticatedRequested": 10,
		"isAuthenticatedCancelled": 11,
		"stageChanged":             12,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_gdm_proto_enumTypes[2].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_gdm_proto_enumTypes[2]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{2}
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          DataType               `protobuf:"varint,1,opt,name=type,proto3,enum=gdm.DataType" json:"type,omitempty"`
	Hello         *HelloData             `protobuf:"bytes,2,opt,name=hello,proto3,oneof" json:"hello,omitempty"`
	Request       *RequestData           `protobuf:"bytes,3,opt,name=request,proto3,oneof" json:"request,omitempty"`
	Response      *ResponseData          `protobuf:"bytes,4,opt,name=response,proto3,oneof" json:"response,omitempty"`
	Event         *EventData             `protobuf:"bytes,5,opt,name=event,proto3,oneof" json:"event,omitempty"`
	PollResponse  []*EventData           `protobuf:"bytes,6,rep,name=pollResponse,proto3" json:"pollResponse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_gdm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_gdm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_unknownType
}

func (x *Data) GetHello() *HelloData {
	if x != nil {
		return x.Hello
	}
	return nil
}

func (x *Data) GetRequest() *RequestData {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *Data) GetResponse() *ResponseData {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *Data) GetEvent() *EventData {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Data) GetPollResponse() []*EventData {
	if x != nil {
		return x.PollResponse
	}
	return nil
}

type HelloData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloData) Reset() {
	*x = HelloData{}
	mi := &file_gdm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloData) ProtoMessage() {}

func (x *HelloData) ProtoReflect() protoreflect.Message {
	mi := &file_gdm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloData.ProtoReflect.Descriptor instead.
func (*HelloData) Descriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{1}
}

func (x *HelloData) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Requests struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Requests) Reset() {
	*x = Requests{}
	mi := &file_gdm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Requests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Requests) ProtoMessage() {}

func (x *Requests) ProtoReflect() protoreflect.Message {
	mi := &file_gdm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Requests.ProtoReflect.Descriptor instead.
func (*Requests) Descriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{2}
}

type RequestData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  RequestType            `protobuf:"varint,1,opt,name=type,proto3,enum=gdm.RequestType" json:"type,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*RequestData_UiLayoutCapabilities
	//	*RequestData_ChangeStage
	Data          isRequestData_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestData) Reset() {
	*x = RequestData{}
	mi := &file_gdm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestData) ProtoMessage() {}

func (x *RequestData) ProtoReflect() protoreflect.Message {
	mi := &file_gdm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestData.ProtoReflect.Descriptor instead.
func (*RequestData) Descriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{3}
}

func (x *RequestData) GetType() RequestType {
	if x != nil {
		return x.Type
	}
	return RequestType_unknownRequest
}

func (x *RequestData) GetData() isRequestData_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RequestData) GetUiLayoutCapabilities() *Requests_UiLayoutCapabilities {
	if x != nil {
		if x, ok := x.Data.(*RequestData_UiLayoutCapabilities); ok {
			return x.UiLayoutCapabilities
		}
	}
	return nil
}

func (x *RequestData) GetChangeStage() *Requests_ChangeStage {
	if x != nil {
		if x, ok := x.Data.(*RequestData_ChangeStage); ok {
			return x.ChangeStage
		}
	}
	return nil
}

type isRequestData_Data interface {
	isRequestData_Data()
}

type RequestData_UiLayoutCapabilities struct {
	UiLayoutCapabilities *Requests_UiLayoutCapabilities `protobuf:"bytes,10,opt,name=uiLayoutCapabilities,proto3,oneof"`
}

type RequestData_ChangeStage struct {
	ChangeStage *Requests_ChangeStage `protobuf:"bytes,11,opt,name=changeStage,proto3,oneof"`
}

func (*RequestData_UiLayoutCapabilities) isRequestData_Data() {}

func (*RequestData_ChangeStage) isRequestData_Data() {}

type Responses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Responses) Reset() {
	*x = Responses{}
	mi := &file_gdm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Responses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Responses) ProtoMessage() {}

func (x *Responses) ProtoReflect() protoreflect.Message {
	mi := &file_gdm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Responses.ProtoReflect.Descriptor instead.
func (*Responses) Descriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{4}
}

type ResponseData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  RequestType            `protobuf:"varint,1,opt,name=type,proto3,enum=gdm.RequestType" json:"type,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*ResponseData_Ack
	//	*ResponseData_UiLayoutCapabilities
	Data          isResponseData_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseData) Reset() {
	*x = ResponseData{}
	mi := &file_gdm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseData) ProtoMessage() {}

func (x *ResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_gdm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseData.ProtoReflect.Descriptor instead.
func (*ResponseData) Descriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseData) GetType() RequestType {
	if x != nil {
		return x.Type
	}
	return RequestType_unknownRequest
}

func (x *ResponseData) GetData() isResponseData_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ResponseData) GetAck() *Responses_Ack {
	if x != nil {
		if x, ok := x.Data.(*ResponseData_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ResponseData) GetUiLayoutCapabilities() *Responses_UiLayoutCapabilities {
	if x != nil {
		if x, ok := x.Data.(*ResponseData_UiLayoutCapabilities); ok {
			return x.UiLayoutCapabilities
		}
	}
	return nil
}

type isResponseData_Data interface {
	isResponseData_Data()
}

type ResponseData_Ack struct {
	Ack *Responses_Ack `protobuf:"bytes,10,opt,name=ack,proto3,oneof"`
}

type ResponseData_UiLayoutCapabilities struct {
	UiLayoutCapabilities *Responses_UiLayoutCapabilities `protobuf:"bytes,11,opt,name=uiLayoutCapabilities,proto3,oneof"`
}

func (*ResponseData_Ack) isResponseData_Data() {}

func (*ResponseData_UiLayoutCapabilities) isResponseData_Data() {}

type Events struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Events) Reset() {
	*x = Events{}
	mi := &file_gdm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Events) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Events) ProtoMessage() {}

func (x *Events) ProtoReflect() protoreflect.Message {
	mi := &file_gdm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Events.ProtoReflect.Descriptor instead.
func (*Events) Descriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{6}
}

type EventData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=gdm.EventType" json:"type,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*EventData_BrokersReceived
	//	*EventData_BrokerSelected
	//	*EventData_AuthModesReceived
	//	*EventData_AuthModeSelected
	//	*EventData_IsAuthenticatedRequested
	//	*EventData_StageChanged
	//	*EventData_UiLayoutReceived
	//	*EventData_AuthEvent
	//	*EventData_ReselectAuthMode
	//	*EventData_StartAuthentication
	//	*EventData_UserSelected
	//	*EventData_IsAuthenticatedCancelled
	Data          isEventData_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventData) Reset() {
	*x = EventData{}
	mi := &file_gdm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventData) ProtoMessage() {}

func (x *EventData) ProtoReflect() protoreflect.Message {
	mi := &file_gdm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventData.ProtoReflect.Descriptor instead.
func (*EventData) Descriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{7}
}

func (x *EventData) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_unknownEvent
}

func (x *EventData) GetData() isEventData_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EventData) GetBrokersReceived() *Events_BrokersReceived {
	if x != nil {
		if x, ok := x.Data.(*EventData_BrokersReceived); ok {
			return x.BrokersReceived
		}
	}
	return nil
}

func (x *EventData) GetBrokerSelected() *Events_BrokerSelected {
	if x != nil {
		if x, ok := x.Data.(*EventData_BrokerSelected); ok {
			return x.BrokerSelected
		}
	}
	return nil
}

func (x *EventData) GetAuthModesReceived() *Events_AuthModesReceived {
	if x != nil {
		if x, ok := x.Data.(*EventData_AuthModesReceived); ok {
			return x.AuthModesReceived
		}
	}
	return nil
}

func (x *EventData) GetAuthModeSelected() *Events_AuthModeSelected {
	if x != nil {
		if x, ok := x.Data.(*EventData_AuthModeSelected); ok {
			return x.AuthModeSelected
		}
	}
	return nil
}

func (x *EventData) GetIsAuthenticatedRequested() *Events_IsAuthenticatedRequested {
	if x != nil {
		if x, ok := x.Data.(*EventData_IsAuthenticatedRequested); ok {
			return x.IsAuthenticatedRequested
		}
	}
	return nil
}

func (x *EventData) GetStageChanged() *Events_StageChanged {
	if x != nil {
		if x, ok := x.Data.(*EventData_StageChanged); ok {
			return x.StageChanged
		}
	}
	return nil
}

func (x *EventData) GetUiLayoutReceived() *Events_UiLayoutReceived {
	if x != nil {
		if x, ok := x.Data.(*EventData_UiLayoutReceived); ok {
			return x.UiLayoutReceived
		}
	}
	return nil
}

func (x *EventData) GetAuthEvent() *Events_AuthEvent {
	if x != nil {
		if x, ok := x.Data.(*EventData_AuthEvent); ok {
			return x.AuthEvent
		}
	}
	return nil
}

func (x *EventData) GetReselectAuthMode() *Events_ReselectAuthMode {
	if x != nil {
		if x, ok := x.Data.(*EventData_ReselectAuthMode); ok {
			return x.ReselectAuthMode
		}
	}
	return nil
}

func (x *EventData) GetStartAuthentication() *Events_StartAuthentication {
	if x != nil {
		if x, ok := x.Data.(*EventData_StartAuthentication); ok {
			return x.StartAuthentication
		}
	}
	return nil
}

func (x *EventData) GetUserSelected() *Events_UserSelected {
	if x != nil {
		if x, ok := x.Data.(*EventData_UserSelected); ok {
			return x.UserSelected
		}
	}
	return nil
}

func (x *EventData) GetIsAuthenticatedCancelled() *Events_IsAuthenticatedCancelled {
	if x != nil {
		if x, ok := x.Data.(*EventData_IsAuthenticatedCancelled); ok {
			return x.IsAuthenticatedCancelled
		}
	}
	return nil
}

type isEventData_Data interface {
	isEventData_Data()
}

type EventData_BrokersReceived struct {
	BrokersReceived *Events_BrokersReceived `protobuf:"bytes,10,opt,name=brokersReceived,proto3,oneof"`
}

type EventData_BrokerSelected struct {
	BrokerSelected *Events_BrokerSelected `protobuf:"bytes,11,opt,name=brokerSelected,proto3,oneof"`
}

type EventData_AuthModesReceived struct {
	AuthModesReceived *Events_AuthModesReceived `protobuf:"bytes,12,opt,name=authModesReceived,proto3,oneof"`
}

type EventData_AuthModeSelected struct {
	AuthModeSelected *Events_AuthModeSelected `protobuf:"bytes,13,opt,name=authModeSelected,proto3,oneof"`
}

type EventData_IsAuthenticatedRequested struct {
	IsAuthenticatedRequested *Events_IsAuthenticatedRequested `protobuf:"bytes,14,opt,name=isAuthenticatedRequested,proto3,oneof"`
}

type EventData_StageChanged struct {
	StageChanged *Events_StageChanged `protobuf:"bytes,15,opt,name=stageChanged,proto3,oneof"`
}

type EventData_UiLayoutReceived struct {
	UiLayoutReceived *Events_UiLayoutReceived `protobuf:"bytes,16,opt,name=uiLayoutReceived,proto3,oneof"`
}

type EventData_AuthEvent struct {
	AuthEvent *Events_AuthEvent `protobuf:"bytes,17,opt,name=authEvent,proto3,oneof"`
}

type EventData_ReselectAuthMode struct {
	ReselectAuthMode *Events_ReselectAuthMode `protobuf:"bytes,18,opt,name=reselectAuthMode,proto3,oneof"`
}

type EventData_StartAuthentication struct {
	StartAuthentication *Events_StartAuthentication `protobuf:"bytes,19,opt,name=startAuthentication,proto3,oneof"`
}

type EventData_UserSelected struct {
	UserSelected *Events_UserSelected `protobuf:"bytes,20,opt,name=userSelected,proto3,oneof"`
}

type EventData_IsAuthenticatedCancelled struct {
	IsAuthenticatedCancelled *Events_IsAuthenticatedCancelled `protobuf:"bytes,21,opt,name=isAuthenticatedCancelled,proto3,oneof"`
}

func (*EventData_BrokersReceived) isEventData_Data() {}

func (*EventData_BrokerSelected) isEventData_Data() {}

func (*EventData_AuthModesReceived) isEventData_Data() {}

func (*EventData_AuthModeSelected) isEventData_Data() {}

func (*EventData_IsAuthenticatedRequested) isEventData_Data() {}

func (*EventData_StageChanged) isEventData_Data() {}

func (*EventData_UiLayoutReceived) isEventData_Data() {}

func (*EventData_AuthEvent) isEventData_Data() {}

func (*EventData_ReselectAuthMode) isEventData_Data() {}

func (*EventData_StartAuthentication) isEventData_Data() {}

func (*EventData_UserSelected) isEventData_Data() {}

func (*EventData_IsAuthenticatedCancelled) isEventData_Data() {}

type Requests_UiLayoutCapabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Requests_UiLayoutCapabilities) Reset() {
	*x = Requests_UiLayoutCapabilities{}
	mi := &file_gdm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Requests_UiLayoutCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Requests_UiLayoutCapabilities) ProtoMessage() {}

func (x *Requests_UiLayoutCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_gdm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Requests_UiLayoutCapabilities.ProtoReflect.Descriptor instead.
func (*Requests_UiLayoutCapabilities) Descriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{2, 0}
}

type Requests_ChangeStage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         proto.Stage            `protobuf:"varint,1,opt,name=stage,proto3,enum=pam.Stage" json:"stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Requests_ChangeStage) Reset() {
	*x = Requests_ChangeStage{}
	mi := &file_gdm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Requests_ChangeStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Requests_ChangeStage) ProtoMessage() {}

func (x *Requests_ChangeStage) ProtoReflect() protoreflect.Message {
	mi := &file_gdm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Requests_ChangeStage.ProtoReflect.Descriptor instead.
func (*Requests_ChangeStage) Descriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Requests_ChangeStage) GetStage() proto.Stage {
	if x != nil {
		return x.Stage
	}
	return proto.Stage(0)
}

type Responses_Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Responses_Ack) Reset() {
	*x = Responses_Ack{}
	mi := &file_gdm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Responses_Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Responses_Ack) ProtoMessage() {}

func (x *Responses_Ack) ProtoReflect() protoreflect.Message {
	mi := &file_gdm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Responses_Ack.ProtoReflect.Descriptor instead.
func (*Responses_Ack) Descriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{4, 0}
}

type Responses_UiLayoutCapabilities struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SupportedUiLayouts []*authd.UILayout      `protobuf:"bytes,10,rep,name=supportedUiLayouts,proto3" json:"supportedUiLayouts,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Responses_UiLayoutCapabilities) Reset() {
	*x = Responses_UiLayoutCapabilities{}
	mi := &file_gdm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Responses_UiLayoutCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Responses_UiLayoutCapabilities) ProtoMessage() {}

func (x *Responses_UiLayoutCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_gdm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Responses_UiLayoutCapabilities.ProtoReflect.Descriptor instead.
func (*Responses_UiLayoutCapabilities) Descriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{4, 1}
}

func (x *Responses_UiLayoutCapabilities) GetSupportedUiLayouts() []*authd.UILayout {
	if x != nil {
		return x.SupportedUiLayouts
	}
	return nil
}

type Events_BrokersReceived struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	BrokersInfos  []*authd.ABResponse_BrokerInfo `protobuf:"bytes,1,rep,name=brokersInfos,proto3" json:"brokersInfos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Events_BrokersReceived) Reset() {
	*x = Events_BrokersReceived{}
	mi := &file_gdm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Events_BrokersReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Events_BrokersReceived) ProtoMessage() {}

func (x *Events_BrokersReceived) ProtoReflect() protoreflect.Message {
	mi := &file_gdm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Events_BrokersReceived.ProtoReflect.Descriptor instead.
func (*Events_BrokersReceived) Descriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{6, 0}
}

func (x *Events_BrokersReceived) GetBrokersInfos() []*authd.ABResponse_BrokerInfo {
	if x != nil {
		return x.BrokersInfos
	}
	return nil
}

type Events_BrokerSelected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerId      string                 `protobuf:"bytes,1,opt,name=brokerId,proto3" json:"brokerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Events_BrokerSelected) Reset() {
	*x = Events_BrokerSelected{}
	mi := &file_gdm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Events_BrokerSelected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Events_BrokerSelected) ProtoMessage() {}

func (x *Events_BrokerSelected) ProtoReflect() protoreflect.Message {
	mi := &file_gdm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Events_BrokerSelected.ProtoReflect.Descriptor instead.
func (*Events_BrokerSelected) Descriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{6, 1}
}

func (x *Events_BrokerSelected) GetBrokerId() string {
	if x != nil {
		return x.BrokerId
	}
	return ""
}

type Events_UserSelected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Events_UserSelected) Reset() {
	*x = Events_UserSelected{}
	mi := &file_gdm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Events_UserSelected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Events_UserSelected) ProtoMessage() {}

func (x *Events_UserSelected) ProtoReflect() protoreflect.Message {
	mi := &file_gdm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Events_UserSelected.ProtoReflect.Descriptor instead.
func (*Events_UserSelected) Descriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{6, 2}
}

func (x *Events_UserSelected) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Events_StartAuthentication struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Events_StartAuthentication) Reset() {
	*x = Events_StartAuthentication{}
	mi := &file_gdm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Events_StartAuthentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Events_StartAuthentication) ProtoMessage() {}

func (x *Events_StartAuthentication) ProtoReflect() protoreflect.Message {
	mi := &file_gdm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Events_StartAuthentication.ProtoReflect.Descriptor instead.
func (*Events_StartAuthentication) Descriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{6, 3}
}

type Events_AuthModesReceived struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	AuthModes     []*authd.GAMResponse_AuthenticationMode `protobuf:"bytes,1,rep,name=authModes,proto3" json:"authModes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Events_AuthModesReceived) Reset() {
	*x = Events_AuthModesReceived{}
	mi := &file_gdm_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Events_AuthModesReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Events_AuthModesReceived) ProtoMessage() {}

func (x *Events_AuthModesReceived) ProtoReflect() protoreflect.Message {
	mi := &file_gdm_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Events_AuthModesReceived.ProtoReflect.Descriptor instead.
func (*Events_AuthModesReceived) Descriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{6, 4}
}

func (x *Events_AuthModesReceived) GetAuthModes() []*authd.GAMResponse_AuthenticationMode {
	if x != nil {
		return x.AuthModes
	}
	return nil
}

type Events_AuthModeSelected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthModeId    string                 `protobuf:"bytes,1,opt,name=authModeId,proto3" json:"authModeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Events_AuthModeSelected) Reset() {
	*x = Events_AuthModeSelected{}
	mi := &file_gdm_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Events_AuthModeSelected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Events_AuthModeSelected) ProtoMessage() {}

func (x *Events_AuthModeSelected) ProtoReflect() protoreflect.Message {
	mi := &file_gdm_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Events_AuthModeSelected.ProtoReflect.Descriptor instead.
func (*Events_AuthModeSelected) Descriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{6, 5}
}

func (x *Events_AuthModeSelected) GetAuthModeId() string {
	if x != nil {
		return x.AuthModeId
	}
	return ""
}

type Events_AuthEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *authd.IAResponse      `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Events_AuthEvent) Reset() {
	*x = Events_AuthEvent{}
	mi := &file_gdm_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Events_AuthEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Events_AuthEvent) ProtoMessage() {}

func (x *Events_AuthEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gdm_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Events_AuthEvent.ProtoReflect.Descriptor instead.
func (*Events_AuthEvent) Descriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{6, 6}
}

func (x *Events_AuthEvent) GetResponse() *authd.IAResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type Events_ReselectAuthMode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Events_ReselectAuthMode) Reset() {
	*x = Events_ReselectAuthMode{}
	mi := &file_gdm_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Events_ReselectAuthMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Events_ReselectAuthMode) ProtoMessage() {}

func (x *Events_ReselectAuthMode) ProtoReflect() protoreflect.Message {
	mi := &file_gdm_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Events_ReselectAuthMode.ProtoReflect.Descriptor instead.
func (*Events_ReselectAuthMode) Descriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{6, 7}
}

type Events_IsAuthenticatedRequested struct {
	state              protoimpl.MessageState              `protogen:"open.v1"`
	AuthenticationData *authd.IARequest_AuthenticationData `protobuf:"bytes,1,opt,name=authentication_data,json=authenticationData,proto3" json:"authentication_data,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Events_IsAuthenticatedRequested) Reset() {
	*x = Events_IsAuthenticatedRequested{}
	mi := &file_gdm_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Events_IsAuthenticatedRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Events_IsAuthenticatedRequested) ProtoMessage() {}

func (x *Events_IsAuthenticatedRequested) ProtoReflect() protoreflect.Message {
	mi := &file_gdm_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Events_IsAuthenticatedRequested.ProtoReflect.Descriptor instead.
func (*Events_IsAuthenticatedRequested) Descriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{6, 8}
}

func (x *Events_IsAuthenticatedRequested) GetAuthenticationData() *authd.IARequest_AuthenticationData {
	if x != nil {
		return x.AuthenticationData
	}
	return nil
}

type Events_IsAuthenticatedCancelled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Events_IsAuthenticatedCancelled) Reset() {
	*x = Events_IsAuthenticatedCancelled{}
	mi := &file_gdm_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Events_IsAuthenticatedCancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Events_IsAuthenticatedCancelled) ProtoMessage() {}

func (x *Events_IsAuthenticatedCancelled) ProtoReflect() protoreflect.Message {
	mi := &file_gdm_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Events_IsAuthenticatedCancelled.ProtoReflect.Descriptor instead.
func (*Events_IsAuthenticatedCancelled) Descriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{6, 9}
}

type Events_StageChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         proto.Stage            `protobuf:"varint,1,opt,name=stage,proto3,enum=pam.Stage" json:"stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Events_StageChanged) Reset() {
	*x = Events_StageChanged{}
	mi := &file_gdm_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Events_StageChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Events_StageChanged) ProtoMessage() {}

func (x *Events_StageChanged) ProtoReflect() protoreflect.Message {
	mi := &file_gdm_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Events_StageChanged.ProtoReflect.Descriptor instead.
func (*Events_StageChanged) Descriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{6, 10}
}

func (x *Events_StageChanged) GetStage() proto.Stage {
	if x != nil {
		return x.Stage
	}
	return proto.Stage(0)
}

type Events_UiLayoutReceived struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UiLayout      *authd.UILayout        `protobuf:"bytes,1,opt,name=uiLayout,proto3" json:"uiLayout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Events_UiLayoutReceived) Reset() {
	*x = Events_UiLayoutReceived{}
	mi := &file_gdm_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Events_UiLayoutReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Events_UiLayoutReceived) ProtoMessage() {}

func (x *Events_UiLayoutReceived) ProtoReflect() protoreflect.Message {
	mi := &file_gdm_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Events_UiLayoutReceived.ProtoReflect.Descriptor instead.
func (*Events_UiLayoutReceived) Descriptor() ([]byte, []int) {
	return file_gdm_proto_rawDescGZIP(), []int{6, 11}
}

func (x *Events_UiLayoutReceived) GetUiLayout() *authd.UILayout {
	if x != nil {
		return x.UiLayout
	}
	return nil
}

var File_gdm_proto protoreflect.FileDescriptor

const file_gdm_proto_rawDesc = "" +
	"\n" +
	"\tgdm.proto\x12\x03gdm\x1a\vauthd.proto\x1a\tpam.proto\"\xc5\x02\n" +
	"\x04Data\x12!\n" +
	"\x04type\x18\x01 \x01(\x0e2\r.gdm.DataTypeR\x04type\x12)\n" +
	"\x05hello\x18\x02 \x01(\v2\x0e.gdm.HelloDataH\x00R\x05hello\x88\x01\x01\x12/\n" +
	"\arequest\x18\x03 \x01(\v2\x10.gdm.RequestDataH\x01R\arequest\x88\x01\x01\x122\n" +
	"\bresponse\x18\x04 \x01(\v2\x11.gdm.ResponseDataH\x02R\bresponse\x88\x01\x01\x12)\n" +
	"\x05event\x18\x05 \x01(\v2\x0e.gdm.EventDataH\x03R\x05event\x88\x01\x01\x122\n" +
	"\fpollResponse\x18\x06 \x03(\v2\x0e.gdm.EventDataR\fpollResponseB\b\n" +
	"\x06_helloB\n" +
	"\n" +
	"\b_requestB\v\n" +
	"\t_responseB\b\n" +
	"\x06_event\"%\n" +
	"\tHelloData\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\"S\n" +
	"\bRequests\x1a\x16\n" +
	"\x14UiLayoutCapabilities\x1a/\n" +
	"\vChangeStage\x12 \n" +
	"\x05stage\x18\x01 \x01(\x0e2\n" +
	".pam.StageR\x05stage\"\xd4\x01\n" +
	"\vRequestData\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.gdm.RequestTypeR\x04type\x12X\n" +
	"\x14uiLayoutCapabilities\x18\n" +
	" \x01(\v2\".gdm.Requests.UiLayoutCapabilitiesH\x00R\x14uiLayoutCapabilities\x12=\n" +
	"\vchangeStage\x18\v \x01(\v2\x19.gdm.Requests.ChangeStageH\x00R\vchangeStageB\x06\n" +
	"\x04data\"k\n" +
	"\tResponses\x1a\x05\n" +
	"\x03Ack\x1aW\n" +
	"\x14UiLayoutCapabilities\x12?\n" +
	"\x12supportedUiLayouts\x18\n" +
	" \x03(\v2\x0f.authd.UILayoutR\x12supportedUiLayouts\"\xbf\x01\n" +
	"\fResponseData\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.gdm.RequestTypeR\x04type\x12&\n" +
	"\x03ack\x18\n" +
	" \x01(\v2\x12.gdm.Responses.AckH\x00R\x03ack\x12Y\n" +
	"\x14uiLayoutCapabilities\x18\v \x01(\v2#.gdm.Responses.UiLayoutCapabilitiesH\x00R\x14uiLayoutCapabilitiesB\x06\n" +
	"\x04data\"\xa9\x05\n" +
	"\x06Events\x1aS\n" +
	"\x0fBrokersReceived\x12@\n" +
	"\fbrokersInfos\x18\x01 \x03(\v2\x1c.authd.ABResponse.BrokerInfoR\fbrokersInfos\x1a,\n" +
	"\x0eBrokerSelected\x12\x1a\n" +
	"\bbrokerId\x18\x01 \x01(\tR\bbrokerId\x1a&\n" +
	"\fUserSelected\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x1a\x15\n" +
	"\x13StartAuthentication\x1aX\n" +
	"\x11AuthModesReceived\x12C\n" +
	"\tauthModes\x18\x01 \x03(\v2%.authd.GAMResponse.AuthenticationModeR\tauthModes\x1a2\n" +
	"\x10AuthModeSelected\x12\x1e\n" +
	"\n" +
	"authModeId\x18\x01 \x01(\tR\n" +
	"authModeId\x1a:\n" +
	"\tAuthEvent\x12-\n" +
	"\bresponse\x18\x01 \x01(\v2\x11.authd.IAResponseR\bresponse\x1a\x12\n" +
	"\x10ReselectAuthMode\x1ap\n" +
	"\x18IsAuthenticatedRequested\x12T\n" +
	"\x13authentication_data\x18\x01 \x01(\v2#.authd.IARequest.AuthenticationDataR\x12authenticationData\x1a\x1a\n" +
	"\x18IsAuthenticatedCancelled\x1a0\n" +
	"\fStageChanged\x12 \n" +
	"\x05stage\x18\x01 \x01(\x0e2\n" +
	".pam.StageR\x05stage\x1a?\n" +
	"\x10UiLayoutReceived\x12+\n" +
	"\buiLayout\x18\x01 \x01(\v2\x0f.authd.UILayoutR\buiLayout\"\xcd\a\n" +
	"\tEventData\x12\"\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0e.gdm.EventTypeR\x04type\x12G\n" +
	"\x0fbrokersReceived\x18\n" +
	" \x01(\v2\x1b.gdm.Events.BrokersReceivedH\x00R\x0fbrokersReceived\x12D\n" +
	"\x0ebrokerSelected\x18\v \x01(\v2\x1a.gdm.Events.BrokerSelectedH\x00R\x0ebrokerSelected\x12M\n" +
	"\x11authModesReceived\x18\f \x01(\v2\x1d.gdm.Events.AuthModesReceivedH\x00R\x11authModesReceived\x12J\n" +
	"\x10authModeSelected\x18\r \x01(\v2\x1c.gdm.Events.AuthModeSelectedH\x00R\x10authModeSelected\x12b\n" +
	"\x18isAuthenticatedRequested\x18\x0e \x01(\v2$.gdm.Events.IsAuthenticatedRequestedH\x00R\x18isAuthenticatedRequested\x12>\n" +
	"\fstageChanged\x18\x0f \x01(\v2\x18.gdm.Events.StageChangedH\x00R\fstageChanged\x12J\n" +
	"\x10uiLayoutReceived\x18\x10 \x01(\v2\x1c.gdm.Events.UiLayoutReceivedH\x00R\x10uiLayoutReceived\x125\n" +
	"\tauthEvent\x18\x11 \x01(\v2\x15.gdm.Events.AuthEventH\x00R\tauthEvent\x12J\n" +
	"\x10reselectAuthMode\x18\x12 \x01(\v2\x1c.gdm.Events.ReselectAuthModeH\x00R\x10reselectAuthMode\x12S\n" +
	"\x13startAuthentication\x18\x13 \x01(\v2\x1f.gdm.Events.StartAuthenticationH\x00R\x13startAuthentication\x12>\n" +
	"\fuserSelected\x18\x14 \x01(\v2\x18.gdm.Events.UserSelectedH\x00R\fuserSelected\x12b\n" +
	"\x18isAuthenticatedCancelled\x18\x15 \x01(\v2$.gdm.Events.IsAuthenticatedCancelledH\x00R\x18isAuthenticatedCancelledB\x06\n" +
	"\x04data*v\n" +
	"\bDataType\x12\x0f\n" +
	"\vunknownType\x10\x00\x12\t\n" +
	"\x05hello\x10\x01\x12\t\n" +
	"\x05event\x10\x02\x12\f\n" +
	"\beventAck\x10\x03\x12\v\n" +
	"\arequest\x10\x04\x12\f\n" +
	"\bresponse\x10\x05\x12\b\n" +
	"\x04poll\x10\x06\x12\x10\n" +
	"\fpollResponse\x10\a*\x82\x01\n" +
	"\vRequestType\x12\x12\n" +
	"\x0eunknownRequest\x10\x00\x12\x15\n" +
	"\x11updateBrokersList\x10\x01\x12\x1d\n" +
	"\x19composeAuthenticationView\x10\x02\x12\x18\n" +
	"\x14uiLayoutCapabilities\x10\x03\x12\x0f\n" +
	"\vchangeStage\x10\x04*\xa7\x02\n" +
	"\tEventType\x12\x10\n" +
	"\funknownEvent\x10\x00\x12\x10\n" +
	"\fuserSelected\x10\x01\x12\x13\n" +
	"\x0fbrokersReceived\x10\x02\x12\x12\n" +
	"\x0ebrokerSelected\x10\x03\x12\x15\n" +
	"\x11authModesReceived\x10\x04\x12\x14\n" +
	"\x10authModeSelected\x10\x05\x12\x14\n" +
	"\x10reselectAuthMode\x10\x06\x12\r\n" +
	"\tauthEvent\x10\a\x12\x14\n" +
	"\x10uiLayoutReceived\x10\b\x12\x17\n" +
	"\x13startAuthentication\x10\t\x12\x1c\n" +
	"\x18isAuthenticatedRequested\x10\n" +
	"\x12\x1c\n" +
	"\x18isAuthenticatedCancelled\x10\v\x12\x10\n" +
	"\fstageChanged\x10\fB!Z\x1fgithub.com/ubuntu/authd/pam/gdmb\x06proto3"

var (
	file_gdm_proto_rawDescOnce sync.Once
	file_gdm_proto_rawDescData []byte
)

func file_gdm_proto_rawDescGZIP() []byte {
	file_gdm_proto_rawDescOnce.Do(func() {
		file_gdm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gdm_proto_rawDesc), len(file_gdm_proto_rawDesc)))
	})
	return file_gdm_proto_rawDescData
}

var file_gdm_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_gdm_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_gdm_proto_goTypes = []any{
	(DataType)(0),                                // 0: gdm.DataType
	(RequestType)(0),                             // 1: gdm.RequestType
	(EventType)(0),                               // 2: gdm.EventType
	(*Data)(nil),                                 // 3: gdm.Data
	(*HelloData)(nil),                            // 4: gdm.HelloData
	(*Requests)(nil),                             // 5: gdm.Requests
	(*RequestData)(nil),                          // 6: gdm.RequestData
	(*Responses)(nil),                            // 7: gdm.Responses
	(*ResponseData)(nil),                         // 8: gdm.ResponseData
	(*Events)(nil),                               // 9: gdm.Events
	(*EventData)(nil),                            // 10: gdm.EventData
	(*Requests_UiLayoutCapabilities)(nil),        // 11: gdm.Requests.UiLayoutCapabilities
	(*Requests_ChangeStage)(nil),                 // 12: gdm.Requests.ChangeStage
	(*Responses_Ack)(nil),                        // 13: gdm.Responses.Ack
	(*Responses_UiLayoutCapabilities)(nil),       // 14: gdm.Responses.UiLayoutCapabilities
	(*Events_BrokersReceived)(nil),               // 15: gdm.Events.BrokersReceived
	(*Events_BrokerSelected)(nil),                // 16: gdm.Events.BrokerSelected
	(*Events_UserSelected)(nil),                  // 17: gdm.Events.UserSelected
	(*Events_StartAuthentication)(nil),           // 18: gdm.Events.StartAuthentication
	(*Events_AuthModesReceived)(nil),             // 19: gdm.Events.AuthModesReceived
	(*Events_AuthModeSelected)(nil),              // 20: gdm.Events.AuthModeSelected
	(*Events_AuthEvent)(nil),                     // 21: gdm.Events.AuthEvent
	(*Events_ReselectAuthMode)(nil),              // 22: gdm.Events.ReselectAuthMode
	(*Events_IsAuthenticatedRequested)(nil),      // 23: gdm.Events.IsAuthenticatedRequested
	(*Events_IsAuthenticatedCancelled)(nil),      // 24: gdm.Events.IsAuthenticatedCancelled
	(*Events_StageChanged)(nil),                  // 25: gdm.Events.StageChanged
	(*Events_UiLayoutReceived)(nil),              // 26: gdm.Events.UiLayoutReceived
	(proto.Stage)(0),                             // 27: pam.Stage
	(*authd.UILayout)(nil),                       // 28: authd.UILayout
	(*authd.ABResponse_BrokerInfo)(nil),          // 29: authd.ABResponse.BrokerInfo
	(*authd.GAMResponse_AuthenticationMode)(nil), // 30: authd.GAMResponse.AuthenticationMode
	(*authd.IAResponse)(nil),                     // 31: authd.IAResponse
	(*authd.IARequest_AuthenticationData)(nil),   // 32: authd.IARequest.AuthenticationData
}
var file_gdm_proto_depIdxs = []int32{
	0,  // 0: gdm.Data.type:type_name -> gdm.DataType
	4,  // 1: gdm.Data.hello:type_name -> gdm.HelloData
	6,  // 2: gdm.Data.request:type_name -> gdm.RequestData
	8,  // 3: gdm.Data.response:type_name -> gdm.ResponseData
	10, // 4: gdm.Data.event:type_name -> gdm.EventData
	10, // 5: gdm.Data.pollResponse:type_name -> gdm.EventData
	1,  // 6: gdm.RequestData.type:type_name -> gdm.RequestType
	11, // 7: gdm.RequestData.uiLayoutCapabilities:type_name -> gdm.Requests.UiLayoutCapabilities
	12, // 8: gdm.RequestData.changeStage:type_name -> gdm.Requests.ChangeStage
	1,  // 9: gdm.ResponseData.type:type_name -> gdm.RequestType
	13, // 10: gdm.ResponseData.ack:type_name -> gdm.Responses.Ack
	14, // 11: gdm.ResponseData.uiLayoutCapabilities:type_name -> gdm.Responses.UiLayoutCapabilities
	2,  // 12: gdm.EventData.type:type_name -> gdm.EventType
	15, // 13: gdm.EventData.brokersReceived:type_name -> gdm.Events.BrokersReceived
	16, // 14: gdm.EventData.brokerSelected:type_name -> gdm.Events.BrokerSelected
	19, // 15: gdm.EventData.authModesReceived:type_name -> gdm.Events.AuthModesReceived
	20, // 16: gdm.EventData.authModeSelected:type_name -> gdm.Events.AuthModeSelected
	23, // 17: gdm.EventData.isAuthenticatedRequested:type_name -> gdm.Events.IsAuthenticatedRequested
	25, // 18: gdm.EventData.stageChanged:type_name -> gdm.Events.StageChanged
	26, // 19: gdm.EventData.uiLayoutReceived:type_name -> gdm.Events.UiLayoutReceived
	21, // 20: gdm.EventData.authEvent:type_name -> gdm.Events.AuthEvent
	22, // 21: gdm.EventData.reselectAuthMode:type_name -> gdm.Events.ReselectAuthMode
	18, // 22: gdm.EventData.startAuthentication:type_name -> gdm.Events.StartAuthentication
	17, // 23: gdm.EventData.userSelected:type_name -> gdm.Events.UserSelected
	24, // 24: gdm.EventData.isAuthenticatedCancelled:type_name -> gdm.Events.IsAuthenticatedCancelled
	27, // 25: gdm.Requests.ChangeStage.stage:type_name -> pam.Stage
	28, // 26: gdm.Responses.UiLayoutCapabilities.supportedUiLayouts:type_name -> authd.UILayout
	29, // 27: gdm.Events.BrokersReceived.brokersInfos:type_name -> authd.ABResponse.BrokerInfo
	30, // 28: gdm.Events.AuthModesReceived.authModes:type_name -> authd.GAMResponse.AuthenticationMode
	31, // 29: gdm.Events.AuthEvent.response:type_name -> authd.IAResponse
	32, // 30: gdm.Events.IsAuthenticatedRequested.authentication_data:type_name -> authd.IARequest.AuthenticationData
	27, // 31: gdm.Events.StageChanged.stage:type_name -> pam.Stage
	28, // 32: gdm.Events.UiLayoutReceived.uiLayout:type_name -> authd.UILayout
	33, // [33:33] is the sub-list for method output_type
	33, // [33:33] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_gdm_proto_init() }
func file_gdm_proto_init() {
	if File_gdm_proto != nil {
		return
	}
	file_gdm_proto_msgTypes[0].OneofWrappers = []any{}
	file_gdm_proto_msgTypes[3].OneofWrappers = []any{
		(*RequestData_UiLayoutCapabilities)(nil),
		(*RequestData_ChangeStage)(nil),
	}
	file_gdm_proto_msgTypes[5].OneofWrappers = []any{
		(*ResponseData_Ack)(nil),
		(*ResponseData_UiLayoutCapabilities)(nil),
	}
	file_gdm_proto_msgTypes[7].OneofWrappers = []any{
		(*EventData_BrokersReceived)(nil),
		(*EventData_BrokerSelected)(nil),
		(*EventData_AuthModesReceived)(nil),
		(*EventData_AuthModeSelected)(nil),
		(*EventData_IsAuthenticatedRequested)(nil),
		(*EventData_StageChanged)(nil),
		(*EventData_UiLayoutReceived)(nil),
		(*EventData_AuthEvent)(nil),
		(*EventData_ReselectAuthMode)(nil),
		(*EventData_StartAuthentication)(nil),
		(*EventData_UserSelected)(nil),
		(*EventData_IsAuthenticatedCancelled)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gdm_proto_rawDesc), len(file_gdm_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gdm_proto_goTypes,
		DependencyIndexes: file_gdm_proto_depIdxs,
		EnumInfos:         file_gdm_proto_enumTypes,
		MessageInfos:      file_gdm_proto_msgTypes,
	}.Build()
	File_gdm_proto = out.File
	file_gdm_proto_goTypes = nil
	file_gdm_proto_depIdxs = nil
}
