name: Check if CLA is signed
on: [pull_request_target]

jobs:
  cla-check:
    name: Check if CLA is signed
    runs-on: ubuntu-latest
    steps:
      - name: Check if CLA signed
        id: check-cla
        uses: canonical/has-signed-canonical-cla@v1
        with:
          accept-existing-contributors: true
      - name: Annotate exit status
      run: |
        set -eu
        if [ ${{ steps.check-cla.outcome }} == "failure" ]; then
          exit 78  # Neutral status
        fi
