name: Git Checks

on: [pull_request]

jobs:
  block-fixup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.0.0
    - name: Check fixup commits
      id: check-fixup
      uses: 13rac1/block-fixup-merge-action@v2.0.0
      continue-on-error: true
    - name: Annotate exit status
      run: |
        set -eu
        if [ ${{ steps.check-fixup.outcome }} == "failure" ]; then
          exit 78  # Neutral status
        fi
